# Site settings
title: "Project Portfolio for James W Cannon"
description: "Info on previous academic and personal projects"

# Use the Minimal Mistakes remote theme (check for the latest version if needed)
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Optional: enable built-in plugins that work with GitHub Pages
plugins:
  - jekyll-feed