title: James W. Cannon
author:
  name: James Cannon

description: >
  James W. Cannon a passionate Mechanical Engineering student at Auburn University,
  set to graduate in May 2025. He combines academic excellence with a drive to innovate and solve complex engineering challenges.
  Explore my projects and feel free to connect with me to discuss opportunities for collaboration.

theme: minima

# Use the remote_theme option if building with GitHub Pages and you want the latest version of Minima:
# remote_theme: jekyll/minima

plugins:
#  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark
  nav_pages:
    - about.md
  # Uncomment the following line if you want to show excerpts on the homepage.
  # show_excerpts: true
  # Customize the date format if needed.
  # date_format: "%b-%d-%Y"

  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/jacan20"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/james-cannon-meche/"
    - title: Email
      icon: envelope
      url: "mailto:jwc0081@auburn.edu"
